name: Release

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      version:
        required: true
        type: string
      is_beta:
        required: true
        type: string
      release_notes:
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tagged source
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name: ${{ inputs.version }}
          files: |
            artifacts/android-artifacts/*.apk
            artifacts/windows-artifacts/*.zip
            artifacts/windows-artifacts/*.exe
          body: ${{ inputs.release_notes }}
          generate_release_notes: false
          prerelease: ${{ inputs.is_beta == 'true' }}